### ISSUE TITLE
Avoid separate import of gio/glib

### ISSUE THREAD

**Issue by mstuehn** [ostreedev/ostree-rs#12]
I'm new to rust, so please bear with me if i got something wrong or used the library in a wrong way.

As far as my understanding goes, it is necessary to import gio/glib additionally to ostree-rs into a project, so ostree-rs is not self-contained. This is counterintuitive to me, because almost all of the API provided by ostree-rs uses some gio/glib (1) types, but i have to import these libraries into my project myself without really knowing what libraries are needed. Also to avoid incompatibility issues, the according versions should match.

For the user it would be easier, if ostree-rs would be self-contained, so that a user of the library only would need to put ostree-rs into the Cargo.toml and could use the gio/glib library which is already pulled in by ostree-rs itself.

(1): Example:
pub fn new_for_sysroot_path<P: IsA<File>, Q: IsA<File>> with File begin a "gio::File"

**Comment by cgwalters** [comment]
The C library works the same way - it uses glib types as public API.

Now, a huge difference between Rust and C here is that glib has never broken API/ABI, whereas with Rust+Cargo it's easy to do semver bumps, and they do.

So...yes, you'll need to add e.g. `gio = "0.14"` to your dependencies too.

Although, perhaps for a few key targeted ones we could re-export?  We don't use *that* many glib types but I fear it'd be a large maintenance burden.

**Comment by mstuehn** [comment]
Yes, you're right, the C-Library uses the public API for both, the library and the application. But there is one major difference: _public API_, therefore all consumers are using the very same headers/libs. In rust, everybody brings their own library. I've already had the problem of not matching glib/gio versions which lead to some compile errors. (Unfortunately i deleted the project after that, so i'm not able to provide the concrete information any more.)
Why do you expect, re-exporting would result in increased maintenance burden? I would appreciate re-export very much, because then the glib/gio parts would only exist once in the workspace and the user would use the same as the library. Isn't re-exporting only making the headers "visible" to the library user?

However, as I already mentioned, I'm new to rust and do not understand all of it well. If the re-export is not desired, would it be possible to provide the list of dependencies a consumer of the library has to include into his project? That would have helped me a lot.

**Comment by fkrull** [comment]
So gtk-rs (whose binding generator we're re-using) recently changed their crates to re-export their dependencies: https://gtk-rs.org/blog/2021/06/22/new-release.html As far as I can see, they just add the entire dependency crate as a top-level export. Maybe we should do that here as well, then you could reference things like e.g. `ostree::gio::File`.

**Comment by cgwalters** [comment]
Nice find @fkrull !  I missed that in the release notes.  PR in https://github.com/ostreedev/ostree-rs/pull/13

**Comment by mstuehn** [comment]
Thats exactly what i asked for! Thank you!
