### ISSUE TITLE
ostree: RepoTransactionStats is missing all properties

### ISSUE THREAD

**Issue by lucab** [ostreedev/ostree-rs#4]
I was looking into transaction stats and it seems there is something going wrong with the bindings. It looks like the low-level type `ostree-sys` exposes the inner properties, but the high-level one in `ostree` does not:
 * https://docs.rs/ostree-sys/0.7.3/ostree_sys/struct.OstreeRepoTransactionStats.html
 * https://docs.rs/ostree/0.11.0/ostree/struct.RepoTransactionStats.html

Possibly some buggy logic or a misconfiguration in the code generator.

**Comment by lucab** [comment]
I asked for clarification on #rust@gnome.org and it turns out that the auto-generation does not cover this kind of plain struct fields on purpose due to (generally) unclear semantics. For this case, I'll manually implement getters for the relevant fields.

**Comment by cgwalters** [comment]
I believe this is fixed by https://github.com/ostreedev/ostree-rs/pull/6
